### ISSUE TITLE
Render new-lines properly

### ISSUE THREAD

**Issue by peter-gy** [domeccleston/sharegpt#6]
It would be great to represent user input through the shared link more similar to how it is styled in the actual chat app. This is easier to show than to explain:

**Input**

<img width="1788" alt="Screenshot 2022-12-05 at 22 36 24" src="https://user-images.githubusercontent.com/40776291/205747556-2e98a9ab-b87b-4108-ab5d-53b88c5073e8.png">

**Output**

<img width="1788" alt="Screenshot 2022-12-05 at 22 36 51" src="https://user-images.githubusercontent.com/40776291/205747607-2cce57fe-ffbf-4df1-af5d-d4a13f2c6780.png">

Related link: https://shareg.pt/ODh5Olw

**Comment by domeccleston** [comment]
Thanks for letting us know @peter-gy. This was caused by improper table styling, I've fixed it to render tables as OpenAI does.

Interestingly this was hard to repro because usually it refuses to render tables - I had to trick it. See here for an example with the new styling

https://shareg.pt/8yL6liy

**Comment by peter-gy** [comment]
Sure thing @domeccleston, thanks for acting on the issue quickly.

The table rendering works nicely, but the line breaks still do not get styled properly. But I see that domeccleston/sharegpt-app#11 is already open to address this.
